#include <stdio.h>
#include <stdlib.h>
#include <iostream>
#include <string>
#include <list>
#include <vector>
#include <sstream>
#include <algorithm>
#include <iterator>
#include <functional>
#include <map>
#include <boost/foreach.hpp>
#include <boost/tokenizer.hpp>
//#include <boost/lexical_cast.hpp>
